# Generated by Django 5.0 on 2026-04-14 14:54

import django.core.validators
import django.db.models.deletion
import voice_notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_booking_booking_availability_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to=voice_notes.models.voice_note_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "m4a", "webm", "mp4"]
                            )
                        ],
                    ),
                ),
                (
                    "audio_duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "audio_file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("transcript", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if transcription failed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transcribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Staff identifier who created the note",
                        max_length=255,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_notes",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "voice_note",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "-created_at"], name="voice_note_booking_idx"
                    ),
                    models.Index(fields=["status"], name="voice_note_status_idx"),
                ],
            },
        ),
    ]
