# Generated by Django 5.0 on 2026-04-13 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('accommodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accommodations.accommodation')),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apartment',
            },
            bases=('accommodations.accommodation',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('accommodation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accommodations.accommodation')),
                ('room_count', models.PositiveIntegerField(default=1)),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'hotel',
            },
            bases=('accommodations.accommodation',),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('apartment', 'Apartment')], default='', max_length=20),
        ),
    ]
