# Generated by Django 5.0 on 2026-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_apartment_hotel_accommodation_accommodation_type'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['accommodation', 'start_date', 'end_date'], name='booking_availability_idx'),
        ),
    ]
